language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"
    - "pypy"
services:
  - redis-server
install:
  - pip install .
  - pip install -r test_requirements.txt

script:
  - nosetests --with-cover --cover-branches --cover-package=memoize

after_success:
  - coveralls
